permalink:        pretty
# Setup
title:            Kvantitatiivsed mudelid käitumisteadustes praktikumide materjalid
url:              https://github.com/datamartin/datamartin.github.io

# Custom vars
github:
  repo:           https://github.com/datamartin/datamartin.github.io

pages_list:       
  Praktikumid: '/praktikumid'
