theme: jekyll-theme-slate
# Setup
title:            Kvantitatiivsed mudelid käitumisteadustes praktikumide materjalid
url:              https://github.com/datamartin/datamartin.github.io
paginate:         1

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/datamartin/datamartin.github.io

pages_list:       
  Praktikumid: '/praktikumid'
