permalink:        pretty
# Setup
title:            Kvantitatiivsed mudelid käitumisteadustes praktikumide materjalid
url:              https://github.com/datamartin/datamartin.github.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/datamartin/datamartin.github.io

pages_list:       
  Praktikumid: '/praktikumid'

theme: jekyll-theme-slate